name: Build and Push to GHCR.IO

on:
  push:
    branches:
    - main
env:
  IMAGE_VERSION: v0.15.5

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Build:checkout
        uses: actions/checkout@v5
      
      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "thisisfeeder"
          password: ${{ secrets.GHCIO }}

      - name: Build:dockerimage
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/mbanq/moov-wire:${{ env.IMAGE_VERSION }}
          push: true
          build-args: |
            "MOOV_WIRE_VERSION=${{ env.IMAGE_VERSION }}"
